"""Thumbnail rendering and injection.

The expected byte-level shape is not invented here: it was read off a
Snapmaker-Orca-sliced file pulled from the printer (`Nitro_Mesh_Knob_PLA_11m33s
.gcode`, Snapmaker Orca 2.3.5), which the U1 screen renders correctly.
"""

import base64

import pytest

from orca_api.u1 import thumbnail as th

# a 1x1 PNG -- content does not matter, only the encoding around it
PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk"
    "YPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
)


def test_block_matches_the_snapmaker_marker_shape():
    block = th.thumbnail_block(PNG, 48, 48)
    lines = block.split("\n")
    assert lines[0] == "; THUMBNAIL_BLOCK_START"
    assert lines[1] == ""
    assert lines[2] == ";"
    assert lines[3].startswith("; thumbnail begin 48x48 ")
    assert lines[-2] == "; thumbnail end"
    assert lines[-1] == "; THUMBNAIL_BLOCK_END"


def test_declared_length_is_the_base64_length_not_the_raw_byte_count():
    # measured: a 847-byte PNG is declared as 1132. Declaring the raw size makes
    # the screen show nothing, with no error anywhere.
    block = th.thumbnail_block(PNG, 48, 48)
    declared = int(block.split("; thumbnail begin 48x48 ")[1].split("\n")[0])
    assert declared == len(base64.b64encode(PNG).decode())
    assert declared != len(PNG)


def test_payload_lines_are_wrapped_at_78_and_comment_prefixed():
    big = PNG * 200
    block = th.thumbnail_block(big, 300, 300)
    payload = [l for l in block.split("\n")
               if l.startswith("; ") and "thumbnail" not in l.lower()]
    assert len(payload) > 1
    for line in payload:
        assert line.startswith("; ")
        assert len(line) <= 80
    assert len(payload[0]) == 80  # "; " + 78


def test_the_payload_round_trips_back_to_the_png():
    block = th.thumbnail_block(PNG, 48, 48)
    body = block.split("; thumbnail begin 48x48")[1].split("; thumbnail end")[0]
    b64 = "".join(l[2:] for l in body.split("\n") if l.startswith("; "))
    assert base64.b64decode(b64) == PNG


def test_injection_lands_after_the_header_block(tmp_path):
    gcode = tmp_path / "j.gcode"
    gcode.write_text("; HEADER_BLOCK_START\n; generated by X\n; HEADER_BLOCK_END\n\nG28\n")
    th.inject_thumbnails(gcode, [(PNG, 48, 48), (PNG, 300, 300)])

    text = gcode.read_text()
    assert text.index("; HEADER_BLOCK_END") < text.index("; THUMBNAIL_BLOCK_START")
    assert text.index("; THUMBNAIL_BLOCK_END") < text.index("G28")
    assert text.count("; thumbnail begin") == 2
    assert "48x48" in text and "300x300" in text


def test_injection_still_works_without_a_header_block(tmp_path):
    # a config-dump-only file has no HEADER_BLOCK -- prepend rather than lose it
    gcode = tmp_path / "j.gcode"
    gcode.write_text("G28\nG1 X0\n")
    th.inject_thumbnails(gcode, [(PNG, 48, 48)])

    text = gcode.read_text()
    assert text.index("; THUMBNAIL_BLOCK_START") < text.index("G28")
    assert text.rstrip().endswith("G1 X0")


def test_injection_is_idempotent(tmp_path):
    # re-running a job must not stack blocks -- the screen reads the first one
    # and every extra copy is dead weight in a file pushed over wifi
    gcode = tmp_path / "j.gcode"
    gcode.write_text("; HEADER_BLOCK_END\nG28\n")
    th.inject_thumbnails(gcode, [(PNG, 48, 48)])
    th.inject_thumbnails(gcode, [(PNG, 48, 48)])
    assert gcode.read_text().count("; thumbnail begin") == 1


def test_no_images_leaves_the_file_untouched(tmp_path):
    gcode = tmp_path / "j.gcode"
    gcode.write_text("; HEADER_BLOCK_END\nG28\n")
    before = gcode.read_bytes()
    th.inject_thumbnails(gcode, [])
    assert gcode.read_bytes() == before


def test_render_builds_a_scad_that_imports_every_stl(tmp_path, monkeypatch):
    seen = {}

    def fake_run(cmd, **kw):
        scad = [a for a in cmd if a.endswith(".scad")][0]
        seen["source"] = open(scad).read()
        seen["cmd"] = cmd
        out = cmd[cmd.index("-o") + 1]
        open(out, "wb").write(PNG)
        return th.subprocess.CompletedProcess(cmd, 0, b"", b"")

    monkeypatch.setattr(th.subprocess, "run", fake_run)

    a, b = tmp_path / "a.stl", tmp_path / "b.stl"
    a.write_text("solid a\nendsolid a\n")
    b.write_text("solid b\nendsolid b\n")
    png = th.render_preview([a, b], tmp_path / "p.png", size=300)

    assert png.read_bytes() == PNG
    assert str(a) in seen["source"] and str(b) in seen["source"]
    assert "300,300" in " ".join(seen["cmd"])


def test_render_raises_when_openscad_writes_nothing(tmp_path, monkeypatch):
    def fake_run(cmd, **kw):
        return th.subprocess.CompletedProcess(cmd, 0, b"", b"boom")

    monkeypatch.setattr(th.subprocess, "run", fake_run)
    with pytest.raises(th.PreviewError):
        th.render_preview([tmp_path / "a.stl"], tmp_path / "p.png", size=48)


def test_render_raises_on_an_empty_png(tmp_path, monkeypatch):
    # OpenSCAD exits 0 having written a 0-byte file when the GL context fails;
    # an empty thumbnail block is worse than none -- it can wedge the parser
    def fake_run(cmd, **kw):
        open(cmd[cmd.index("-o") + 1], "wb").write(b"")
        return th.subprocess.CompletedProcess(cmd, 0, b"", b"")

    monkeypatch.setattr(th.subprocess, "run", fake_run)
    with pytest.raises(th.PreviewError):
        th.render_preview([tmp_path / "a.stl"], tmp_path / "p.png", size=48)
