"""Interactive setup for Orca Auto configuration."""

import os
import sys
from pathlib import Path
from typing import Optional

import httpx

# ANSI color codes (duplicated from cli.py for standalone usage)
class Colors:
    RESET = "\033[0m"
    RED = "\033[91m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    BOLD = "\033[1m"
    DIM = "\033[2m"


def colorize(text: str, color: str) -> str:
    """Apply color to text if terminal supports it."""
    if not sys.stdout.isatty():
        return text
    return f"{color}{text}{Colors.RESET}"


def prompt_path(
    name: str,
    default: str,
    must_exist: bool = True,
    is_file: bool = False,
    env_var: Optional[str] = None
) -> str:
    """Prompt user for a path with validation.

    Args:
        name: Display name for the prompt
        default: Default value if user enters nothing
        must_exist: Whether the path must already exist
        is_file: If True, validates as file; if False, validates as directory
        env_var: Environment variable to check for current value

    Returns:
        Validated path string
    """
    # Show current value from environment if available
    current = os.environ.get(env_var) if env_var else None
    if current:
        print(f"  Current: {colorize(current, Colors.DIM)}")

    while True:
        try:
            prompt_text = f"{name} [{default}]: "
            user_input = input(colorize(prompt_text, Colors.CYAN)).strip()

            path_value = user_input if user_input else default
            path = Path(path_value)

            if must_exist:
                if is_file:
                    if not path.is_file():
                        print(colorize(f"  Error: File does not exist: {path}", Colors.RED))
                        continue
                    # Check if executable for binary paths
                    if not os.access(path, os.X_OK):
                        print(colorize(f"  Warning: File is not executable: {path}", Colors.YELLOW))
                else:
                    if not path.is_dir():
                        # Offer to create directory
                        create = input(colorize(f"  Directory does not exist. Create it? [Y/n]: ", Colors.YELLOW)).strip().lower()
                        if create in ("", "y", "yes"):
                            try:
                                path.mkdir(parents=True, exist_ok=True)
                                print(colorize(f"  Created: {path}", Colors.GREEN))
                            except OSError as e:
                                print(colorize(f"  Error creating directory: {e}", Colors.RED))
                                continue
                        else:
                            continue

            return str(path)

        except KeyboardInterrupt:
            print()
            raise


def write_env_file(config: dict) -> bool:
    """Write configuration to .env file in current directory.

    Args:
        config: Dictionary of environment variable names to values

    Returns:
        True if successful, False otherwise
    """
    env_path = Path(".env")

    # Read existing .env file if it exists
    existing = {}
    if env_path.exists():
        try:
            with open(env_path, "r") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, _, value = line.partition("=")
                        existing[key.strip()] = value.strip()
        except IOError:
            pass

    # Merge new config with existing
    existing.update(config)

    # Write back
    try:
        with open(env_path, "w") as f:
            f.write("# Orca Auto Configuration\n")
            f.write("# Generated by orca-auto setup\n\n")
            for key, value in sorted(existing.items()):
                f.write(f"{key}={value}\n")
        return True
    except IOError as e:
        print(colorize(f"Error writing .env file: {e}", Colors.RED))
        return False


def upload_profile(api_url: str, file_path: str) -> dict:
    """Upload a printer profile to the API.

    Args:
        api_url: Base URL of the Orca Auto API
        file_path: Path to .orca_printer file

    Returns:
        Dict with import results

    Raises:
        ConnectionError: If cannot connect to API
        ValueError: If upload fails
    """
    url = f"{api_url.rstrip('/')}/api/profiles/import"

    try:
        with open(file_path, "rb") as f:
            files = {"file": (Path(file_path).name, f, "application/octet-stream")}
            with httpx.Client(timeout=60.0) as client:
                response = client.post(url, files=files)

        if response.status_code >= 400:
            detail = "Import failed"
            try:
                detail = response.json().get("detail", detail)
            except Exception:
                pass
            raise ValueError(detail)

        return response.json()

    except httpx.ConnectError:
        raise ConnectionError(f"Cannot connect to API at {api_url}")
    except httpx.TimeoutException:
        raise ConnectionError("Request timed out")
    except IOError as e:
        raise ValueError(f"Cannot read file: {e}")


def run_setup(api_url: str) -> int:
    """Run the interactive setup wizard.

    Args:
        api_url: Base URL of the Orca Auto API

    Returns:
        Exit code (0 for success, 1 for error)
    """
    try:
        # Welcome banner
        print()
        print(colorize("=" * 50, Colors.BOLD))
        print(colorize("       Orca Auto Setup", Colors.BOLD))
        print(colorize("=" * 50, Colors.BOLD))
        print()
        print("This will configure your local .env file and import printer profiles.")
        print()

        config = {}

        # Step 1: STL Library Path
        print(colorize("Step 1: STL Library Path", Colors.BOLD))
        print("  Directory containing your STL files for slicing.")
        models_path = prompt_path(
            "STL Library Path",
            default="/data/models",
            must_exist=True,
            is_file=False,
            env_var="ORCA_MODELS_PATH"
        )
        config["ORCA_MODELS_PATH"] = models_path
        print(colorize(f"  Set: {models_path}", Colors.GREEN))
        print()

        # Step 2: Sliced Output Path
        print(colorize("Step 2: Sliced Output Path", Colors.BOLD))
        print("  Directory where sliced .3mf files will be saved.")
        sliced_path = prompt_path(
            "Sliced Output Path",
            default="/data/output",
            must_exist=True,
            is_file=False,
            env_var="ORCA_SLICED_PATH"
        )
        config["ORCA_SLICED_PATH"] = sliced_path
        print(colorize(f"  Set: {sliced_path}", Colors.GREEN))
        print()

        # Step 3: OrcaSlicer Binary Path
        print(colorize("Step 3: OrcaSlicer Binary Path", Colors.BOLD))
        print("  Path to the OrcaSlicer executable.")
        orcaslicer_bin = prompt_path(
            "OrcaSlicer Binary Path",
            default="/usr/local/bin/orcaslicer",
            must_exist=True,
            is_file=True,
            env_var="ORCA_ORCASLICER_BIN"
        )
        config["ORCA_ORCASLICER_BIN"] = orcaslicer_bin
        print(colorize(f"  Set: {orcaslicer_bin}", Colors.GREEN))
        print()

        # Write configuration
        print(colorize("Writing configuration...", Colors.BOLD))
        if write_env_file(config):
            env_path = Path(".env").resolve()
            print(colorize(f"  Configuration saved to: {env_path}", Colors.GREEN))
        else:
            print(colorize("  Failed to write configuration file.", Colors.RED))
            return 1
        print()

        # Step 4: Profile Import
        print(colorize("Step 4: Import Printer Profiles", Colors.BOLD))
        print("  Import .orca_printer files containing your printer configurations.")
        print()

        profiles_imported = 0
        while True:
            try:
                import_choice = input(colorize("Import printer profile? (.orca_printer file) [y/N]: ", Colors.CYAN)).strip().lower()

                if import_choice not in ("y", "yes"):
                    break

                profile_path = input(colorize("Profile file path: ", Colors.CYAN)).strip()

                if not profile_path:
                    continue

                if not Path(profile_path).is_file():
                    print(colorize(f"  Error: File not found: {profile_path}", Colors.RED))
                    continue

                print(f"  Uploading {Path(profile_path).name}...")

                try:
                    result = upload_profile(api_url, profile_path)
                    imported = result.get("imported", 0)
                    errors = result.get("errors", [])

                    if imported > 0:
                        print(colorize(f"  Imported {imported} profile(s)", Colors.GREEN))
                        profiles_imported += imported

                    if errors:
                        print(colorize(f"  Errors: {', '.join(errors)}", Colors.YELLOW))

                except ConnectionError as e:
                    print(colorize(f"  Connection error: {e}", Colors.RED))
                    print(colorize("  Make sure the API server is running.", Colors.YELLOW))
                except ValueError as e:
                    print(colorize(f"  Import failed: {e}", Colors.RED))

                print()

            except KeyboardInterrupt:
                print()
                break

        # Final summary
        print()
        print(colorize("=" * 50, Colors.BOLD))
        print(colorize("       Setup Complete!", Colors.GREEN + Colors.BOLD))
        print(colorize("=" * 50, Colors.BOLD))
        print()
        print(colorize("Configuration Summary:", Colors.BOLD))
        print(f"  STL Library Path:     {config['ORCA_MODELS_PATH']}")
        print(f"  Sliced Output Path:   {config['ORCA_SLICED_PATH']}")
        print(f"  OrcaSlicer Binary:    {config['ORCA_ORCASLICER_BIN']}")
        print(f"  Profiles imported:    {profiles_imported}")
        print()
        print("Start the API server with:")
        print(colorize("  uvicorn orca_api.main:app", Colors.CYAN))
        print()

        return 0

    except KeyboardInterrupt:
        print()
        print(colorize("\nSetup cancelled.", Colors.YELLOW))
        return 1
